### ISSUE TITLE
Error LNK1104 File libboost_iostreams-vc110-mt-1_50.lib cannot be opened, while building on Windows x64

### ISSUE THREAD

**Issue by radomirkesl** [dcoeurjo/CorrectedNormalCurrent#2]
I am stuck on this error, while building on Windows x64, the named file does not exist indeed, there are however many simmilar, as if there was some versioning problem. Also I have made a few adjustments to get through errors before, I do not think they would cause this, but it is not impossible. Should I maybe first start over? Or is there a solution to this particular error? Thanks for any help.

**Comment by dcoeurjo** [comment]
Dear @radomirkesl 
Thanks for the bug report. The project and its main dependency, `dgtal`, have been heavily tested on linux and macOS, and partially on windows (not really for code related issues but rather the lack of package manager in windows). Note that the part of DGtal that is required to build this project compiles perfectly on windows (cf the Continuous Integration bot Appveyor at DGtal-team/DGtal).

The error you have is related to the fact that your cmake does not find or cannot open the `libboost_iostreams-vc110-mt-1_50.lib`. Using the cmake-gui, please try to manually set the path to the lib when building the project, or edit the visual studio project to fix the path.

The issue seems to be related on your own configuration.

**Comment by radomirkesl** [comment]
Dear @dcoeurjo,

sorry to check in after so much time. So I managed to find a version of Boost, that asks for an existing file. Now I am using boost_1_64_0-msvc-14.1-64. I still get the same error, now asking for libboost_iostreams-vc141-mt-1_64.lib. This file indeed exists, however I am not able to figure out, how to specifically set the path to it. Could you describe how to do that (with cmake-gui preferably)? Thanks a lot.

**Comment by dcoeurjo** [comment]
Unfortunately, I don't have access to a windows machine so I cannot reproduce your issue. If you just want to run our demo, I'd suggest you to just install a linux VM or a cygwin environment and you won't have any issue building the code.

If you want to reuse our differential estimators in your benchmark, the `CorrectedNormalCurrentFormula.h` contains everything you need.

We have a CI bot that is perfectly building DGtal on windows (script: https://github.com/DGtal-team/DGtal/blob/master/appveyor.yml), the variables `BOOST_ROOT` and `BOOST_LIBRARYDIR` are the one you must set (`BOOST_ROOT: "C:\\Libraries\\boost_1_63_0"` and `BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_63_0\\lib32-msvc-14.0"` in our bot)
